name: Deploy current state

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install texlive-full

      - name: Build Docs
        run: |
          make local-all
          echo ${{ github.sha }} > Release.txt

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: virio-msg-draft-v${{ github.run_number }} # Or a more meaningful tag
          release_name: Draft ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: virtio-v1.4-wd01.pdf
          asset_name: virtio-v1.4-wd01.pdf
          asset_content_type: application/pdf
