name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt install texlive-full

      - name: Build HTML
        run: |
          make local-html
